"""Packs assets/export/meshes.json into Luau modules the server turns into MeshParts at boot.

Output: src/shared/Data/MeshData/<Id>.luau (one per piece) and MeshData/init.luau (index).
Each group is stored as base64 of little-endian packed data:
    vertex: int16 x,y,z (1/256 stud) + int8 nx,ny,nz (1/127)   -> 9 bytes
    triangle: uint16 a,b,c                                     -> 6 bytes
Decoded at runtime with string.unpack; see server/Base/MeshFactory.luau.

Run: python3 tools/gen_meshdata.py
"""

from __future__ import annotations

import base64
import json
import os
import struct

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "assets", "export", "meshes.json")
OUT = os.path.join(ROOT, "src", "shared", "Data", "MeshData")

SCALE = 256.0


def pack_group(g: dict) -> tuple[str, str, int, int]:
    verts = g["verts"]
    n = len(verts) // 6
    if n > 65535:
        raise ValueError(f"group {g['name']} has {n} vertices; uint16 indices only")
    vb = bytearray()
    for i in range(n):
        x, y, z, nx, ny, nz = verts[i * 6 : i * 6 + 6]
        vb += struct.pack("<hhhbbb", clamp16(x * SCALE), clamp16(y * SCALE), clamp16(z * SCALE), clamp8(nx * 127), clamp8(ny * 127), clamp8(nz * 127))
    tris = g["tris"]
    tb = bytearray()
    for i in range(0, len(tris), 3):
        tb += struct.pack("<HHH", tris[i], tris[i + 1], tris[i + 2])
    return base64.b64encode(bytes(vb)).decode("ascii"), base64.b64encode(bytes(tb)).decode("ascii"), n, len(tris) // 3


def clamp16(v: float) -> int:
    return max(-32768, min(32767, int(round(v))))


def clamp8(v: float) -> int:
    return max(-127, min(127, int(round(v))))


def lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return lua_str(v)
    if isinstance(v, list):
        return "{ " + ", ".join(lua_value(x) for x in v) + " }"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"[{lua_str(k)}] = {lua_value(x)}" for k, x in v.items()) + " }"
    if v is None:
        return "nil"
    raise TypeError(type(v))


def chunk(s: str, width: int = 100) -> str:
    """Split a long base64 string into concatenated Luau string literals for readable files."""
    parts = [s[i : i + width] for i in range(0, len(s), width)]
    return "table.concat({\n" + "".join(f'\t\t\t"{p}",\n' for p in parts) + "\t\t})"


def main() -> None:
    bundle = json.load(open(SRC, encoding="utf-8"))
    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.endswith(".luau") and f != "init.luau":
            os.remove(os.path.join(OUT, f))
    index = []
    total_bytes = 0
    for pid, piece in bundle["pieces"].items():
        lines = ["--!nonstrict", f"-- Generated by tools/gen_meshdata.py from assets/export/meshes.json. Do not edit.", f"-- {pid}: {piece['triangles']} triangles", "", "return {"]
        lines.append(f"\tid = {lua_str(pid)},")
        lines.append(f"\tcells = {lua_value(piece['cells'])},")
        lines.append(f"\tplaceable = {lua_value(piece['placeable'])},")
        lines.append(f"\tattachments = {lua_value(piece['attachments'])},")
        lines.append(f"\tlights = {lua_value(piece['lights'])},")
        lines.append("\tgroups = {")
        for g in piece["groups"]:
            vb, tb, nv, nt = pack_group(g)
            total_bytes += len(vb) + len(tb)
            lines.append("\t\t{")
            lines.append(f"\t\t\tname = {lua_str(g['name'])},")
            lines.append(f"\t\t\tcolor = {lua_value(g['color'])},")
            lines.append(f"\t\t\ttheme = {lua_value(g['theme'])},")
            lines.append(f"\t\t\tmaterial = {lua_str(g['material'])},")
            lines.append(f"\t\t\tattrs = {lua_value(g['attrs'])},")
            lines.append(f"\t\t\tcollide = {lua_value(g['collide'])},")
            lines.append(f"\t\t\ttransparency = {lua_value(g['transparency'])},")
            lines.append(f"\t\t\tcenter = {lua_value(g['center'])},")
            lines.append(f"\t\t\tsize = {lua_value(g['size'])},")
            lines.append(f"\t\t\tvertexCount = {nv},")
            lines.append(f"\t\t\ttriangleCount = {nt},")
            lines.append(f"\t\t\tvertices = {chunk(vb)},")
            lines.append(f"\t\t\ttriangles = {chunk(tb)},")
            lines.append("\t\t},")
        lines.append("\t},")
        lines.append("}")
        with open(os.path.join(OUT, f"{pid}.luau"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        index.append(pid)
    with open(os.path.join(OUT, "init.luau"), "w", encoding="utf-8") as f:
        f.write("--!strict\n-- Generated by tools/gen_meshdata.py. Lists every mesh module in this folder.\n\nreturn {\n")
        for pid in index:
            f.write(f"\t{lua_str(pid)},\n")
        f.write("} :: { string }\n")
    print(f"wrote {len(index)} mesh modules ({total_bytes // 1024} KB base64) to {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
